#!/usr/bin/env sh
#
# Copyright (C) 2017 Vitalii Dmitriev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Dummy way to get something from the device

readonly P_NAME=${0##*/}
readonly D_D=/data/data
readonly DB=databases
readonly SHORT_OPTS="h,d:,b,l"
readonly LONG_OPTS="help,database:,bugreport,last"
readonly ARGS=$(getopt -s sh --options $SHORT_OPTS --longoptions $LONG_OPTS --name $P_NAME -- "$@")

##################################################
# Shows help message
# Globals:
#   P_NAME
##################################################
usage() {
    cat <<EO
Usage:

    $P_NAME [options] <packagename>
    
Options:

EO
    cat <<EO | column -s\& -t
    -h, --help & Print this help.
    -d, --database <package name> & Get database for a package name.
    -l, --last & Get database for the last asked package name.
    -b, --bugreport & Get all bugreports from device.
EO
}

adb root && adb remount

eval set -- "$ARGS"
case "${1}" in
    -h|--help)
        usage
        ;;
    -d|--database)
        export LAST_PACKAGE=${2}
        adb pull ${D_D}/${2}/${DB}/
        ;;
    -b|--bugreport)
        adb pull /data/bugreports/
        ;;
    -l|--last)
        # TODO don't work, fix
        if [ -z $LAST_PACKAGE ]; then
            echo "No last package! Try ${P_NAME} -d required.package.name."
        else
            adb pull ${D_D}/$LAST_PACKAGE/${DB}/
        fi    
        ;;
esac
