#!/usr/bin/env sh
#
# Copyright (C) 2017 Vitalii Dmitriev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Simple flasher for RPi 2/3.

flashit() {
	device=${1}
	if [ -n ${device} ]; then
		echo "====|Flashing the ${device}!|===="
		date
		sudo fastboot -s ${device} flash boot boot.img
		sudo fastboot -s ${device} -S 768M flash system system.img
		# sudo fastboot -s ${device} -S 768M flash userdata userdata.img
		sudo fastboot -s ${device} flash cache cache.img
		sudo fastboot -s ${device} flash recovery recovery.img
		sudo fastboot -s ${device} reboot
		echo "====|DONE|===="
		date
	fi
}

for arg in $@; do
	flashit ${arg} &
done
