#!/usr/bin/env bash
#
# TODO: make it toggle.
# TODO: make it be recursive only with -r param.

action="${1}"
readonly NAME_ORIG="Android.mk"
readonly NAME_IGNORE=".ignore.Android.mk"

replace() {
    local project=${1}
    local orig_mk_name=${2}
    local repl_mk_name=${3}
    if [ -n $project ]; then
        mk_paths=$(find $project -name $orig_mk_name)
        echo "Original: "$mk_paths
        echo "Move to: "$(dirname $mk_paths)/$repl_mk_name
        for p in $mk_paths; do
             mv $p "$(dirname $p)/$repl_mk_name"
        done
    fi
}

if [[ $action == "i" || $action == "ignore" ]]; then
    replace ${2} $NAME_ORIG $NAME_IGNORE
elif [[ $action == "r" || $action == "restore" ]]; then
    replace ${2} $NAME_IGNORE $NAME_ORIG
else
    echo "No such action! Use i (ignore) or r (restore)."
fi
