#!/bin/sh
#
# Copyright 2016 Vitalii Dmitriev 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This is a dummy script, which pushes some packages to device.
# Note that your $OUT env variable must be set
# (e.g. after an initialization of the Android build environment)
# TODO make smart version with finder which could push files right after they're built.

readonly P_NAME=${0##*/}
readonly SYS_LIB="/system/lib/"
readonly SYS_LIB64="/system/lib64/"
readonly SYS_BIN="/system/bin/"
readonly SYS_FWK="/system/framework/"
readonly SYS_PA="/system/priv-app/"

if [ "h" != ${1} ]; then
    adb root && adb remount
fi

usage() {
    cat <<EO
    Defined path is $SRC_HOME.
    Change it if you have a different directory for your source code.

    Usage: 

EO
    cat <<EO | column -s\& -t
        ${P_NAME} if  & for InputFlinger
        ${P_NAME} fs  & for Framework Services
        ${P_NAME} fsl & for Framework Services with .so libs
        ${P_NAME} fw  & for Framework itself
        ${P_NAME} sui & for SystemUI
        ${P_NAME} all & for all of them
EO
}

main() {
    case ${1} in
        "h")
            usage
            exit 0 
            ;;
        "if")
            echo "[ Install InputFlinger ]"
            adb push "${OUT}${SYS_LIB}libinputflinger.so" ${SYS_LIB}
            adb push "${OUT}${SYS_LIB64}libinputflinger.so" ${SYS_LIB64}
            adb push "${OUT}${SYS_LIB}libinputflingerhost.so" ${SYS_LIB}
            adb push "${OUT}${SYS_LIB64}libinputflingerhost.so" ${SYS_LIB64}
            adb push "${OUT}${SYS_BIN}inputflinger" ${SYS_BIN}
            ;;
        "fs")
            echo "[ Install Framework Services ]"
            adb push "${OUT}${SYS_FWK}services.jar" ${SYS_FWK}
            ;;
        "fsl")
            echo "[ Install Framework Services with .so ]"
            adb push "${OUT}${SYS_FWK}services.jar" ${SYS_FWK}
            adb push "${OUT}${SYS_LIB}libandroid_servers.so" ${SYS_LIB}
            ;;
        "fw")
            echo "[ Install Framework ]"
            adb push "${OUT}${SYS_FWK}framework.jar" ${SYS_FWK}
            adb push "${OUT}${SYS_FWK}ext.jar" ${SYS_FWK}
            ;;
        "sui")
            echo "[ Install SystemUI ]"
            adb push "${OUT}${SYS_PA}/SystemUI/SystemUI.apk" "${SYS_PA}/SystemUI/"
            ;;
        "all")
            echo "[ == Instal everything == ]"
            main "fw"
            main "fs"
            main "fsl"
            main "if"
            main  "sui"
            ;;
    esac
}

main $@
