#!/usr/bin/env bash
#
# Copyright 2018 Vitalii Dmitriev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly NAME_ORIG="Android.mk"
readonly NAME_IGNORE=".ignore.Android.mk"
readonly NAME_IGNORE_2=".Android.mk"
readonly NAME_IGNORE_3="Android.mk.old"
readonly BLUEPRINT="Android.bp"

replace() {
    local project=${1}
    local orig_mk_name=${2}
    local repl_mk_name=${3}
    if [ -n $project ]; then
        mk_paths=$(find $project -name $orig_mk_name)
        echo "Original: "$mk_paths
        echo "Move to: "$(dirname $mk_paths)/$repl_mk_name
        for p in $mk_paths; do
             mv $p "$(dirname $p)/$repl_mk_name"
        done
    fi
}

directory="${1}"
if [ -z $directory ]; then
    directory=$(pwd)
fi

if [ $(find ${directory} -name ${BLUEPRINT}) ]; then
    echo "${directory} has Android.bp, not supported yet!";
elif [ $(find ${directory} -name ${NAME_ORIG}) ]; then
    replace ${directory} $NAME_ORIG $NAME_IGNORE
elif [ $(find ${directory} -name ${NAME_IGNORE}) ]; then
    replace ${directory} $NAME_IGNORE $NAME_ORIG
else
    echo "No Android.mk file found!"
fi
