#!/usr/bin/env bash

readonly NAME_ORIG="Android.mk"
readonly NAME_IGNORE=".ignore.Android.mk"

replace() {
    local project=${1}
    local orig_mk_name=${2}
    local repl_mk_name=${3}
    if [ -n $project ]; then
        mk_paths=$(find $project -name $orig_mk_name)
        echo "Original: "$mk_paths
        echo "Move to: "$(dirname $mk_paths)/$repl_mk_name
        for p in $mk_paths; do
             mv $p "$(dirname $p)/$repl_mk_name"
        done
    fi
}

action="${1}"
directory="${2}"
if [ -z $directory ]; then
    directory=$(pwd)
fi

if [[ $action == "e" || $action == "exclude" ]]; then
    replace ${directory} $NAME_ORIG $NAME_IGNORE
elif [[ $action == "i" || $action == "include" ]]; then
    replace ${directory} $NAME_IGNORE $NAME_ORIG
else
    echo "No such action! Use e (exclude) or i (include)."
fi
