#!/usr/bin/env bash

readonly NAME_ORIG="Android.mk"
readonly NAME_IGNORE=".ignore.Android.mk"
readonly BLUEPRINT="Android.bp"

replace() {
    local project=${1}
    local orig_mk_name=${2}
    local repl_mk_name=${3}
    if [ -n $project ]; then
        mk_paths=$(find $project -name $orig_mk_name)
        echo "Original: "$mk_paths
        echo "Move to: "$(dirname $mk_paths)/$repl_mk_name
        for p in $mk_paths; do
             mv $p "$(dirname $p)/$repl_mk_name"
        done
    fi
}

directory="${1}"
if [ -z $directory ]; then
    directory=$(pwd)
fi

if [ $(find ${directory} -name ${BLUEPRINT}) ]; then
    echo "${directory} has Android.bp, not supported yet!";
elif [ $(find ${directory} -name ${NAME_ORIG}) ]; then
    replace ${directory} $NAME_ORIG $NAME_IGNORE
elif [ $(find ${directory} -name ${NAME_IGNORE}) ]; then
    replace ${directory} $NAME_IGNORE $NAME_ORIG
else
    echo "No Android.mk file found!"
fi
