#!/bin/bash
#
# Copyright 2016 Vitalii Dmitriev 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enables/disables trackpoint for IBM/Lenovo Thinkpad laptops before *40
# (e.g. for x230 works, for x240 doesn't).
# TODO: add *40 models and higher.

input=$(xinput watch-props  "TPPS/2 IBM TrackPoint" "" | grep 318)
enabled="${input: -1}"

if [[ $enabled == 0 || -z $enabled ]]; then
    xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
    xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
    xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
else
    xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 0
fi
